// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ordering/proto/inventory.proto

package inventorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skus          []string               `protobuf:"bytes,1,rep,name=skus,proto3" json:"skus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityRequest) Reset() {
	*x = CheckAvailabilityRequest{}
	mi := &file_ordering_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityRequest) ProtoMessage() {}

func (x *CheckAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_ordering_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAvailabilityRequest) GetSkus() []string {
	if x != nil {
		return x.Skus
	}
	return nil
}

type CheckAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         map[string]*StockLevel `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityResponse) Reset() {
	*x = CheckAvailabilityResponse{}
	mi := &file_ordering_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityResponse) ProtoMessage() {}

func (x *CheckAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_ordering_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAvailabilityResponse) GetItems() map[string]*StockLevel {
	if x != nil {
		return x.Items
	}
	return nil
}

type StockLevel struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Sku               string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AisleType         string                 `protobuf:"bytes,3,opt,name=aisle_type,json=aisleType,proto3" json:"aisle_type,omitempty"`
	QuantityAvailable int32                  `protobuf:"varint,4,opt,name=quantity_available,json=quantityAvailable,proto3" json:"quantity_available,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StockLevel) Reset() {
	*x = StockLevel{}
	mi := &file_ordering_proto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockLevel) ProtoMessage() {}

func (x *StockLevel) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockLevel.ProtoReflect.Descriptor instead.
func (*StockLevel) Descriptor() ([]byte, []int) {
	return file_ordering_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *StockLevel) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *StockLevel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StockLevel) GetAisleType() string {
	if x != nil {
		return x.AisleType
	}
	return ""
}

func (x *StockLevel) GetQuantityAvailable() int32 {
	if x != nil {
		return x.QuantityAvailable
	}
	return 0
}

type ReserveItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         map[string]int32       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItemsRequest) Reset() {
	*x = ReserveItemsRequest{}
	mi := &file_ordering_proto_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItemsRequest) ProtoMessage() {}

func (x *ReserveItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItemsRequest.ProtoReflect.Descriptor instead.
func (*ReserveItemsRequest) Descriptor() ([]byte, []int) {
	return file_ordering_proto_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveItemsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveItemsRequest) GetItems() map[string]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReserveItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItemsResponse) Reset() {
	*x = ReserveItemsResponse{}
	mi := &file_ordering_proto_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItemsResponse) ProtoMessage() {}

func (x *ReserveItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItemsResponse.ProtoReflect.Descriptor instead.
func (*ReserveItemsResponse) Descriptor() ([]byte, []int) {
	return file_ordering_proto_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveItemsResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveItemsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveItemsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ReleaseItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         map[string]int32       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseItemsRequest) Reset() {
	*x = ReleaseItemsRequest{}
	mi := &file_ordering_proto_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseItemsRequest) ProtoMessage() {}

func (x *ReleaseItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseItemsRequest.ProtoReflect.Descriptor instead.
func (*ReleaseItemsRequest) Descriptor() ([]byte, []int) {
	return file_ordering_proto_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseItemsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReleaseItemsRequest) GetItems() map[string]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReleaseItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseItemsResponse) Reset() {
	*x = ReleaseItemsResponse{}
	mi := &file_ordering_proto_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseItemsResponse) ProtoMessage() {}

func (x *ReleaseItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseItemsResponse.ProtoReflect.Descriptor instead.
func (*ReleaseItemsResponse) Descriptor() ([]byte, []int) {
	return file_ordering_proto_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseItemsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ProcessCustomerOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         map[string]int32       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessCustomerOrderRequest) Reset() {
	*x = ProcessCustomerOrderRequest{}
	mi := &file_ordering_proto_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessCustomerOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessCustomerOrderRequest) ProtoMessage() {}

func (x *ProcessCustomerOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessCustomerOrderRequest.ProtoReflect.Descriptor instead.
func (*ProcessCustomerOrderRequest) Descriptor() ([]byte, []int) {
	return file_ordering_proto_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessCustomerOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ProcessCustomerOrderRequest) GetItems() map[string]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

type ProcessCustomerOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessCustomerOrderResponse) Reset() {
	*x = ProcessCustomerOrderResponse{}
	mi := &file_ordering_proto_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessCustomerOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessCustomerOrderResponse) ProtoMessage() {}

func (x *ProcessCustomerOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessCustomerOrderResponse.ProtoReflect.Descriptor instead.
func (*ProcessCustomerOrderResponse) Descriptor() ([]byte, []int) {
	return file_ordering_proto_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessCustomerOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessCustomerOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RestockItemsOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*RestockItem         `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestockItemsOrderRequest) Reset() {
	*x = RestockItemsOrderRequest{}
	mi := &file_ordering_proto_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestockItemsOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestockItemsOrderRequest) ProtoMessage() {}

func (x *RestockItemsOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestockItemsOrderRequest.ProtoReflect.Descriptor instead.
func (*RestockItemsOrderRequest) Descriptor() ([]byte, []int) {
	return file_ordering_proto_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *RestockItemsOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RestockItemsOrderRequest) GetItems() []*RestockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RestockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AisleType     string                 `protobuf:"bytes,3,opt,name=aisle_type,json=aisleType,proto3" json:"aisle_type,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitCost      float64                `protobuf:"fixed64,5,opt,name=unit_cost,json=unitCost,proto3" json:"unit_cost,omitempty"`
	MfdDate       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=mfd_date,json=mfdDate,proto3" json:"mfd_date,omitempty"`
	ExpiryDate    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestockItem) Reset() {
	*x = RestockItem{}
	mi := &file_ordering_proto_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestockItem) ProtoMessage() {}

func (x *RestockItem) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestockItem.ProtoReflect.Descriptor instead.
func (*RestockItem) Descriptor() ([]byte, []int) {
	return file_ordering_proto_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *RestockItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *RestockItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestockItem) GetAisleType() string {
	if x != nil {
		return x.AisleType
	}
	return ""
}

func (x *RestockItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RestockItem) GetUnitCost() float64 {
	if x != nil {
		return x.UnitCost
	}
	return 0
}

func (x *RestockItem) GetMfdDate() *timestamppb.Timestamp {
	if x != nil {
		return x.MfdDate
	}
	return nil
}

func (x *RestockItem) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

type RestockItemsOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestockItemsOrderResponse) Reset() {
	*x = RestockItemsOrderResponse{}
	mi := &file_ordering_proto_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestockItemsOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestockItemsOrderResponse) ProtoMessage() {}

func (x *RestockItemsOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestockItemsOrderResponse.ProtoReflect.Descriptor instead.
func (*RestockItemsOrderResponse) Descriptor() ([]byte, []int) {
	return file_ordering_proto_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *RestockItemsOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReportJobStatusRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OrderId string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// string robot_id = 2; // Deprecated/Removed
	Status         string           `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ProcessedItems map[string]int32 `protobuf:"bytes,4,rep,name=processed_items,json=processedItems,proto3" json:"processed_items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// 🆕 ADD THIS FIELD
	OrderType     string `protobuf:"bytes,5,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportJobStatusRequest) Reset() {
	*x = ReportJobStatusRequest{}
	mi := &file_ordering_proto_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportJobStatusRequest) ProtoMessage() {}

func (x *ReportJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportJobStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_ordering_proto_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *ReportJobStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReportJobStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportJobStatusRequest) GetProcessedItems() map[string]int32 {
	if x != nil {
		return x.ProcessedItems
	}
	return nil
}

func (x *ReportJobStatusRequest) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

type ReportJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportJobStatusResponse) Reset() {
	*x = ReportJobStatusResponse{}
	mi := &file_ordering_proto_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportJobStatusResponse) ProtoMessage() {}

func (x *ReportJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportJobStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_ordering_proto_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *ReportJobStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_ordering_proto_inventory_proto protoreflect.FileDescriptor

const file_ordering_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1eordering/proto/inventory.proto\x12\tinventory\x1a\x1fgoogle/protobuf/timestamp.proto\".\n" +
	"\x18CheckAvailabilityRequest\x12\x12\n" +
	"\x04skus\x18\x01 \x03(\tR\x04skus\"\xb3\x01\n" +
	"\x19CheckAvailabilityResponse\x12E\n" +
	"\x05items\x18\x01 \x03(\v2/.inventory.CheckAvailabilityResponse.ItemsEntryR\x05items\x1aO\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.inventory.StockLevelR\x05value:\x028\x01\"\x80\x01\n" +
	"\n" +
	"StockLevel\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"aisle_type\x18\x03 \x01(\tR\taisleType\x12-\n" +
	"\x12quantity_available\x18\x04 \x01(\x05R\x11quantityAvailable\"\xab\x01\n" +
	"\x13ReserveItemsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12?\n" +
	"\x05items\x18\x02 \x03(\v2).inventory.ReserveItemsRequest.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"p\n" +
	"\x14ReserveItemsResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xab\x01\n" +
	"\x13ReleaseItemsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12?\n" +
	"\x05items\x18\x02 \x03(\v2).inventory.ReleaseItemsRequest.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"0\n" +
	"\x14ReleaseItemsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xbb\x01\n" +
	"\x1bProcessCustomerOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12G\n" +
	"\x05items\x18\x02 \x03(\v21.inventory.ProcessCustomerOrderRequest.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"R\n" +
	"\x1cProcessCustomerOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"c\n" +
	"\x18RestockItemsOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.inventory.RestockItemR\x05items\"\xff\x01\n" +
	"\vRestockItem\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"aisle_type\x18\x03 \x01(\tR\taisleType\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x1b\n" +
	"\tunit_cost\x18\x05 \x01(\x01R\bunitCost\x125\n" +
	"\bmfd_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\amfdDate\x12;\n" +
	"\vexpiry_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\"5\n" +
	"\x19RestockItemsOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8d\x02\n" +
	"\x16ReportJobStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12^\n" +
	"\x0fprocessed_items\x18\x04 \x03(\v25.inventory.ReportJobStatusRequest.ProcessedItemsEntryR\x0eprocessedItems\x12\x1d\n" +
	"\n" +
	"order_type\x18\x05 \x01(\tR\torderType\x1aA\n" +
	"\x13ProcessedItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"3\n" +
	"\x17ReportJobStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb7\x04\n" +
	"\x10InventoryService\x12^\n" +
	"\x11CheckAvailability\x12#.inventory.CheckAvailabilityRequest\x1a$.inventory.CheckAvailabilityResponse\x12O\n" +
	"\fReserveItems\x12\x1e.inventory.ReserveItemsRequest\x1a\x1f.inventory.ReserveItemsResponse\x12O\n" +
	"\fReleaseItems\x12\x1e.inventory.ReleaseItemsRequest\x1a\x1f.inventory.ReleaseItemsResponse\x12^\n" +
	"\x11RestockItemsOrder\x12#.inventory.RestockItemsOrderRequest\x1a$.inventory.RestockItemsOrderResponse\x12g\n" +
	"\x14ProcessCustomerOrder\x12&.inventory.ProcessCustomerOrderRequest\x1a'.inventory.ProcessCustomerOrderResponse\x12X\n" +
	"\x0fReportJobStatus\x12!.inventory.ReportJobStatusRequest\x1a\".inventory.ReportJobStatusResponseB)Z'auto_grocery/ordering/proto;inventorypbb\x06proto3"

var (
	file_ordering_proto_inventory_proto_rawDescOnce sync.Once
	file_ordering_proto_inventory_proto_rawDescData []byte
)

func file_ordering_proto_inventory_proto_rawDescGZIP() []byte {
	file_ordering_proto_inventory_proto_rawDescOnce.Do(func() {
		file_ordering_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ordering_proto_inventory_proto_rawDesc), len(file_ordering_proto_inventory_proto_rawDesc)))
	})
	return file_ordering_proto_inventory_proto_rawDescData
}

var file_ordering_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_ordering_proto_inventory_proto_goTypes = []any{
	(*CheckAvailabilityRequest)(nil),     // 0: inventory.CheckAvailabilityRequest
	(*CheckAvailabilityResponse)(nil),    // 1: inventory.CheckAvailabilityResponse
	(*StockLevel)(nil),                   // 2: inventory.StockLevel
	(*ReserveItemsRequest)(nil),          // 3: inventory.ReserveItemsRequest
	(*ReserveItemsResponse)(nil),         // 4: inventory.ReserveItemsResponse
	(*ReleaseItemsRequest)(nil),          // 5: inventory.ReleaseItemsRequest
	(*ReleaseItemsResponse)(nil),         // 6: inventory.ReleaseItemsResponse
	(*ProcessCustomerOrderRequest)(nil),  // 7: inventory.ProcessCustomerOrderRequest
	(*ProcessCustomerOrderResponse)(nil), // 8: inventory.ProcessCustomerOrderResponse
	(*RestockItemsOrderRequest)(nil),     // 9: inventory.RestockItemsOrderRequest
	(*RestockItem)(nil),                  // 10: inventory.RestockItem
	(*RestockItemsOrderResponse)(nil),    // 11: inventory.RestockItemsOrderResponse
	(*ReportJobStatusRequest)(nil),       // 12: inventory.ReportJobStatusRequest
	(*ReportJobStatusResponse)(nil),      // 13: inventory.ReportJobStatusResponse
	nil,                                  // 14: inventory.CheckAvailabilityResponse.ItemsEntry
	nil,                                  // 15: inventory.ReserveItemsRequest.ItemsEntry
	nil,                                  // 16: inventory.ReleaseItemsRequest.ItemsEntry
	nil,                                  // 17: inventory.ProcessCustomerOrderRequest.ItemsEntry
	nil,                                  // 18: inventory.ReportJobStatusRequest.ProcessedItemsEntry
	(*timestamppb.Timestamp)(nil),        // 19: google.protobuf.Timestamp
}
var file_ordering_proto_inventory_proto_depIdxs = []int32{
	14, // 0: inventory.CheckAvailabilityResponse.items:type_name -> inventory.CheckAvailabilityResponse.ItemsEntry
	15, // 1: inventory.ReserveItemsRequest.items:type_name -> inventory.ReserveItemsRequest.ItemsEntry
	16, // 2: inventory.ReleaseItemsRequest.items:type_name -> inventory.ReleaseItemsRequest.ItemsEntry
	17, // 3: inventory.ProcessCustomerOrderRequest.items:type_name -> inventory.ProcessCustomerOrderRequest.ItemsEntry
	10, // 4: inventory.RestockItemsOrderRequest.items:type_name -> inventory.RestockItem
	19, // 5: inventory.RestockItem.mfd_date:type_name -> google.protobuf.Timestamp
	19, // 6: inventory.RestockItem.expiry_date:type_name -> google.protobuf.Timestamp
	18, // 7: inventory.ReportJobStatusRequest.processed_items:type_name -> inventory.ReportJobStatusRequest.ProcessedItemsEntry
	2,  // 8: inventory.CheckAvailabilityResponse.ItemsEntry.value:type_name -> inventory.StockLevel
	0,  // 9: inventory.InventoryService.CheckAvailability:input_type -> inventory.CheckAvailabilityRequest
	3,  // 10: inventory.InventoryService.ReserveItems:input_type -> inventory.ReserveItemsRequest
	5,  // 11: inventory.InventoryService.ReleaseItems:input_type -> inventory.ReleaseItemsRequest
	9,  // 12: inventory.InventoryService.RestockItemsOrder:input_type -> inventory.RestockItemsOrderRequest
	7,  // 13: inventory.InventoryService.ProcessCustomerOrder:input_type -> inventory.ProcessCustomerOrderRequest
	12, // 14: inventory.InventoryService.ReportJobStatus:input_type -> inventory.ReportJobStatusRequest
	1,  // 15: inventory.InventoryService.CheckAvailability:output_type -> inventory.CheckAvailabilityResponse
	4,  // 16: inventory.InventoryService.ReserveItems:output_type -> inventory.ReserveItemsResponse
	6,  // 17: inventory.InventoryService.ReleaseItems:output_type -> inventory.ReleaseItemsResponse
	11, // 18: inventory.InventoryService.RestockItemsOrder:output_type -> inventory.RestockItemsOrderResponse
	8,  // 19: inventory.InventoryService.ProcessCustomerOrder:output_type -> inventory.ProcessCustomerOrderResponse
	13, // 20: inventory.InventoryService.ReportJobStatus:output_type -> inventory.ReportJobStatusResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_ordering_proto_inventory_proto_init() }
func file_ordering_proto_inventory_proto_init() {
	if File_ordering_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ordering_proto_inventory_proto_rawDesc), len(file_ordering_proto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ordering_proto_inventory_proto_goTypes,
		DependencyIndexes: file_ordering_proto_inventory_proto_depIdxs,
		MessageInfos:      file_ordering_proto_inventory_proto_msgTypes,
	}.Build()
	File_ordering_proto_inventory_proto = out.File
	file_ordering_proto_inventory_proto_goTypes = nil
	file_ordering_proto_inventory_proto_depIdxs = nil
}
