// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: inventory.proto

#include "inventory.pb.h"
#include "inventory.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace inventory {

static const char* InventoryService_method_names[] = {
  "/inventory.InventoryService/CheckAvailability",
  "/inventory.InventoryService/ReserveItems",
  "/inventory.InventoryService/ReleaseItems",
  "/inventory.InventoryService/RestockItemsOrder",
  "/inventory.InventoryService/ProcessCustomerOrder",
  "/inventory.InventoryService/ReportJobStatus",
};

std::unique_ptr< InventoryService::Stub> InventoryService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< InventoryService::Stub> stub(new InventoryService::Stub(channel, options));
  return stub;
}

InventoryService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CheckAvailability_(InventoryService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReserveItems_(InventoryService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReleaseItems_(InventoryService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RestockItemsOrder_(InventoryService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ProcessCustomerOrder_(InventoryService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReportJobStatus_(InventoryService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status InventoryService::Stub::CheckAvailability(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest& request, ::inventory::CheckAvailabilityResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::inventory::CheckAvailabilityRequest, ::inventory::CheckAvailabilityResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CheckAvailability_, context, request, response);
}

void InventoryService::Stub::async::CheckAvailability(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest* request, ::inventory::CheckAvailabilityResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::inventory::CheckAvailabilityRequest, ::inventory::CheckAvailabilityResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckAvailability_, context, request, response, std::move(f));
}

void InventoryService::Stub::async::CheckAvailability(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest* request, ::inventory::CheckAvailabilityResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckAvailability_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::inventory::CheckAvailabilityResponse>* InventoryService::Stub::PrepareAsyncCheckAvailabilityRaw(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::inventory::CheckAvailabilityResponse, ::inventory::CheckAvailabilityRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CheckAvailability_, context, request);
}

::grpc::ClientAsyncResponseReader< ::inventory::CheckAvailabilityResponse>* InventoryService::Stub::AsyncCheckAvailabilityRaw(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCheckAvailabilityRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status InventoryService::Stub::ReserveItems(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest& request, ::inventory::ReserveItemsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::inventory::ReserveItemsRequest, ::inventory::ReserveItemsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReserveItems_, context, request, response);
}

void InventoryService::Stub::async::ReserveItems(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest* request, ::inventory::ReserveItemsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::inventory::ReserveItemsRequest, ::inventory::ReserveItemsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReserveItems_, context, request, response, std::move(f));
}

void InventoryService::Stub::async::ReserveItems(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest* request, ::inventory::ReserveItemsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReserveItems_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::inventory::ReserveItemsResponse>* InventoryService::Stub::PrepareAsyncReserveItemsRaw(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::inventory::ReserveItemsResponse, ::inventory::ReserveItemsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReserveItems_, context, request);
}

::grpc::ClientAsyncResponseReader< ::inventory::ReserveItemsResponse>* InventoryService::Stub::AsyncReserveItemsRaw(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReserveItemsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status InventoryService::Stub::ReleaseItems(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest& request, ::inventory::ReleaseItemsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::inventory::ReleaseItemsRequest, ::inventory::ReleaseItemsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReleaseItems_, context, request, response);
}

void InventoryService::Stub::async::ReleaseItems(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest* request, ::inventory::ReleaseItemsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::inventory::ReleaseItemsRequest, ::inventory::ReleaseItemsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReleaseItems_, context, request, response, std::move(f));
}

void InventoryService::Stub::async::ReleaseItems(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest* request, ::inventory::ReleaseItemsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReleaseItems_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::inventory::ReleaseItemsResponse>* InventoryService::Stub::PrepareAsyncReleaseItemsRaw(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::inventory::ReleaseItemsResponse, ::inventory::ReleaseItemsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReleaseItems_, context, request);
}

::grpc::ClientAsyncResponseReader< ::inventory::ReleaseItemsResponse>* InventoryService::Stub::AsyncReleaseItemsRaw(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReleaseItemsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status InventoryService::Stub::RestockItemsOrder(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest& request, ::inventory::RestockItemsOrderResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::inventory::RestockItemsOrderRequest, ::inventory::RestockItemsOrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RestockItemsOrder_, context, request, response);
}

void InventoryService::Stub::async::RestockItemsOrder(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest* request, ::inventory::RestockItemsOrderResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::inventory::RestockItemsOrderRequest, ::inventory::RestockItemsOrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RestockItemsOrder_, context, request, response, std::move(f));
}

void InventoryService::Stub::async::RestockItemsOrder(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest* request, ::inventory::RestockItemsOrderResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RestockItemsOrder_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::inventory::RestockItemsOrderResponse>* InventoryService::Stub::PrepareAsyncRestockItemsOrderRaw(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::inventory::RestockItemsOrderResponse, ::inventory::RestockItemsOrderRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RestockItemsOrder_, context, request);
}

::grpc::ClientAsyncResponseReader< ::inventory::RestockItemsOrderResponse>* InventoryService::Stub::AsyncRestockItemsOrderRaw(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRestockItemsOrderRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status InventoryService::Stub::ProcessCustomerOrder(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest& request, ::inventory::ProcessCustomerOrderResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::inventory::ProcessCustomerOrderRequest, ::inventory::ProcessCustomerOrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ProcessCustomerOrder_, context, request, response);
}

void InventoryService::Stub::async::ProcessCustomerOrder(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest* request, ::inventory::ProcessCustomerOrderResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::inventory::ProcessCustomerOrderRequest, ::inventory::ProcessCustomerOrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProcessCustomerOrder_, context, request, response, std::move(f));
}

void InventoryService::Stub::async::ProcessCustomerOrder(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest* request, ::inventory::ProcessCustomerOrderResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProcessCustomerOrder_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::inventory::ProcessCustomerOrderResponse>* InventoryService::Stub::PrepareAsyncProcessCustomerOrderRaw(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::inventory::ProcessCustomerOrderResponse, ::inventory::ProcessCustomerOrderRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ProcessCustomerOrder_, context, request);
}

::grpc::ClientAsyncResponseReader< ::inventory::ProcessCustomerOrderResponse>* InventoryService::Stub::AsyncProcessCustomerOrderRaw(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncProcessCustomerOrderRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status InventoryService::Stub::ReportJobStatus(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest& request, ::inventory::ReportJobStatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::inventory::ReportJobStatusRequest, ::inventory::ReportJobStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReportJobStatus_, context, request, response);
}

void InventoryService::Stub::async::ReportJobStatus(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest* request, ::inventory::ReportJobStatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::inventory::ReportJobStatusRequest, ::inventory::ReportJobStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportJobStatus_, context, request, response, std::move(f));
}

void InventoryService::Stub::async::ReportJobStatus(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest* request, ::inventory::ReportJobStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportJobStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::inventory::ReportJobStatusResponse>* InventoryService::Stub::PrepareAsyncReportJobStatusRaw(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::inventory::ReportJobStatusResponse, ::inventory::ReportJobStatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReportJobStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::inventory::ReportJobStatusResponse>* InventoryService::Stub::AsyncReportJobStatusRaw(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReportJobStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

InventoryService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InventoryService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InventoryService::Service, ::inventory::CheckAvailabilityRequest, ::inventory::CheckAvailabilityResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InventoryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::inventory::CheckAvailabilityRequest* req,
             ::inventory::CheckAvailabilityResponse* resp) {
               return service->CheckAvailability(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InventoryService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InventoryService::Service, ::inventory::ReserveItemsRequest, ::inventory::ReserveItemsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InventoryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::inventory::ReserveItemsRequest* req,
             ::inventory::ReserveItemsResponse* resp) {
               return service->ReserveItems(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InventoryService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InventoryService::Service, ::inventory::ReleaseItemsRequest, ::inventory::ReleaseItemsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InventoryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::inventory::ReleaseItemsRequest* req,
             ::inventory::ReleaseItemsResponse* resp) {
               return service->ReleaseItems(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InventoryService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InventoryService::Service, ::inventory::RestockItemsOrderRequest, ::inventory::RestockItemsOrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InventoryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::inventory::RestockItemsOrderRequest* req,
             ::inventory::RestockItemsOrderResponse* resp) {
               return service->RestockItemsOrder(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InventoryService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InventoryService::Service, ::inventory::ProcessCustomerOrderRequest, ::inventory::ProcessCustomerOrderResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InventoryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::inventory::ProcessCustomerOrderRequest* req,
             ::inventory::ProcessCustomerOrderResponse* resp) {
               return service->ProcessCustomerOrder(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InventoryService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InventoryService::Service, ::inventory::ReportJobStatusRequest, ::inventory::ReportJobStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InventoryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::inventory::ReportJobStatusRequest* req,
             ::inventory::ReportJobStatusResponse* resp) {
               return service->ReportJobStatus(ctx, req, resp);
             }, this)));
}

InventoryService::Service::~Service() {
}

::grpc::Status InventoryService::Service::CheckAvailability(::grpc::ServerContext* context, const ::inventory::CheckAvailabilityRequest* request, ::inventory::CheckAvailabilityResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status InventoryService::Service::ReserveItems(::grpc::ServerContext* context, const ::inventory::ReserveItemsRequest* request, ::inventory::ReserveItemsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status InventoryService::Service::ReleaseItems(::grpc::ServerContext* context, const ::inventory::ReleaseItemsRequest* request, ::inventory::ReleaseItemsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status InventoryService::Service::RestockItemsOrder(::grpc::ServerContext* context, const ::inventory::RestockItemsOrderRequest* request, ::inventory::RestockItemsOrderResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status InventoryService::Service::ProcessCustomerOrder(::grpc::ServerContext* context, const ::inventory::ProcessCustomerOrderRequest* request, ::inventory::ProcessCustomerOrderResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status InventoryService::Service::ReportJobStatus(::grpc::ServerContext* context, const ::inventory::ReportJobStatusRequest* request, ::inventory::ReportJobStatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace inventory
#include <grpcpp/ports_undef.inc>

