// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/inventory.proto
#ifndef GRPC_proto_2finventory_2eproto__INCLUDED
#define GRPC_proto_2finventory_2eproto__INCLUDED

#include "proto/inventory.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace inventory {

class InventoryService final {
 public:
  static constexpr char const* service_full_name() {
    return "inventory.InventoryService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CheckAvailability(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest& request, ::inventory::CheckAvailabilityResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::CheckAvailabilityResponse>> AsyncCheckAvailability(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::CheckAvailabilityResponse>>(AsyncCheckAvailabilityRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::CheckAvailabilityResponse>> PrepareAsyncCheckAvailability(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::CheckAvailabilityResponse>>(PrepareAsyncCheckAvailabilityRaw(context, request, cq));
    }
    virtual ::grpc::Status ReserveItems(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest& request, ::inventory::ReserveItemsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReserveItemsResponse>> AsyncReserveItems(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReserveItemsResponse>>(AsyncReserveItemsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReserveItemsResponse>> PrepareAsyncReserveItems(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReserveItemsResponse>>(PrepareAsyncReserveItemsRaw(context, request, cq));
    }
    virtual ::grpc::Status ReleaseItems(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest& request, ::inventory::ReleaseItemsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReleaseItemsResponse>> AsyncReleaseItems(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReleaseItemsResponse>>(AsyncReleaseItemsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReleaseItemsResponse>> PrepareAsyncReleaseItems(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReleaseItemsResponse>>(PrepareAsyncReleaseItemsRaw(context, request, cq));
    }
    virtual ::grpc::Status ProcessCustomerOrder(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest& request, ::inventory::ProcessCustomerOrderResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ProcessCustomerOrderResponse>> AsyncProcessCustomerOrder(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ProcessCustomerOrderResponse>>(AsyncProcessCustomerOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ProcessCustomerOrderResponse>> PrepareAsyncProcessCustomerOrder(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ProcessCustomerOrderResponse>>(PrepareAsyncProcessCustomerOrderRaw(context, request, cq));
    }
    virtual ::grpc::Status RestockItemsOrder(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest& request, ::inventory::RestockItemsOrderResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::RestockItemsOrderResponse>> AsyncRestockItemsOrder(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::RestockItemsOrderResponse>>(AsyncRestockItemsOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::RestockItemsOrderResponse>> PrepareAsyncRestockItemsOrder(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::RestockItemsOrderResponse>>(PrepareAsyncRestockItemsOrderRaw(context, request, cq));
    }
    virtual ::grpc::Status ReportJobStatus(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest& request, ::inventory::ReportJobStatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReportJobStatusResponse>> AsyncReportJobStatus(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReportJobStatusResponse>>(AsyncReportJobStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReportJobStatusResponse>> PrepareAsyncReportJobStatus(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReportJobStatusResponse>>(PrepareAsyncReportJobStatusRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CheckAvailability(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest* request, ::inventory::CheckAvailabilityResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CheckAvailability(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest* request, ::inventory::CheckAvailabilityResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ReserveItems(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest* request, ::inventory::ReserveItemsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReserveItems(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest* request, ::inventory::ReserveItemsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ReleaseItems(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest* request, ::inventory::ReleaseItemsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReleaseItems(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest* request, ::inventory::ReleaseItemsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ProcessCustomerOrder(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest* request, ::inventory::ProcessCustomerOrderResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ProcessCustomerOrder(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest* request, ::inventory::ProcessCustomerOrderResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void RestockItemsOrder(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest* request, ::inventory::RestockItemsOrderResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RestockItemsOrder(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest* request, ::inventory::RestockItemsOrderResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ReportJobStatus(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest* request, ::inventory::ReportJobStatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReportJobStatus(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest* request, ::inventory::ReportJobStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::inventory::CheckAvailabilityResponse>* AsyncCheckAvailabilityRaw(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::inventory::CheckAvailabilityResponse>* PrepareAsyncCheckAvailabilityRaw(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReserveItemsResponse>* AsyncReserveItemsRaw(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReserveItemsResponse>* PrepareAsyncReserveItemsRaw(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReleaseItemsResponse>* AsyncReleaseItemsRaw(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReleaseItemsResponse>* PrepareAsyncReleaseItemsRaw(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ProcessCustomerOrderResponse>* AsyncProcessCustomerOrderRaw(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ProcessCustomerOrderResponse>* PrepareAsyncProcessCustomerOrderRaw(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::inventory::RestockItemsOrderResponse>* AsyncRestockItemsOrderRaw(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::inventory::RestockItemsOrderResponse>* PrepareAsyncRestockItemsOrderRaw(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReportJobStatusResponse>* AsyncReportJobStatusRaw(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::inventory::ReportJobStatusResponse>* PrepareAsyncReportJobStatusRaw(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CheckAvailability(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest& request, ::inventory::CheckAvailabilityResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::CheckAvailabilityResponse>> AsyncCheckAvailability(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::CheckAvailabilityResponse>>(AsyncCheckAvailabilityRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::CheckAvailabilityResponse>> PrepareAsyncCheckAvailability(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::CheckAvailabilityResponse>>(PrepareAsyncCheckAvailabilityRaw(context, request, cq));
    }
    ::grpc::Status ReserveItems(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest& request, ::inventory::ReserveItemsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::ReserveItemsResponse>> AsyncReserveItems(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::ReserveItemsResponse>>(AsyncReserveItemsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::ReserveItemsResponse>> PrepareAsyncReserveItems(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::ReserveItemsResponse>>(PrepareAsyncReserveItemsRaw(context, request, cq));
    }
    ::grpc::Status ReleaseItems(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest& request, ::inventory::ReleaseItemsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::ReleaseItemsResponse>> AsyncReleaseItems(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::ReleaseItemsResponse>>(AsyncReleaseItemsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::ReleaseItemsResponse>> PrepareAsyncReleaseItems(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::ReleaseItemsResponse>>(PrepareAsyncReleaseItemsRaw(context, request, cq));
    }
    ::grpc::Status ProcessCustomerOrder(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest& request, ::inventory::ProcessCustomerOrderResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::ProcessCustomerOrderResponse>> AsyncProcessCustomerOrder(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::ProcessCustomerOrderResponse>>(AsyncProcessCustomerOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::ProcessCustomerOrderResponse>> PrepareAsyncProcessCustomerOrder(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::ProcessCustomerOrderResponse>>(PrepareAsyncProcessCustomerOrderRaw(context, request, cq));
    }
    ::grpc::Status RestockItemsOrder(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest& request, ::inventory::RestockItemsOrderResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::RestockItemsOrderResponse>> AsyncRestockItemsOrder(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::RestockItemsOrderResponse>>(AsyncRestockItemsOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::RestockItemsOrderResponse>> PrepareAsyncRestockItemsOrder(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::RestockItemsOrderResponse>>(PrepareAsyncRestockItemsOrderRaw(context, request, cq));
    }
    ::grpc::Status ReportJobStatus(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest& request, ::inventory::ReportJobStatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::ReportJobStatusResponse>> AsyncReportJobStatus(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::ReportJobStatusResponse>>(AsyncReportJobStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::ReportJobStatusResponse>> PrepareAsyncReportJobStatus(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inventory::ReportJobStatusResponse>>(PrepareAsyncReportJobStatusRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CheckAvailability(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest* request, ::inventory::CheckAvailabilityResponse* response, std::function<void(::grpc::Status)>) override;
      void CheckAvailability(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest* request, ::inventory::CheckAvailabilityResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReserveItems(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest* request, ::inventory::ReserveItemsResponse* response, std::function<void(::grpc::Status)>) override;
      void ReserveItems(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest* request, ::inventory::ReserveItemsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReleaseItems(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest* request, ::inventory::ReleaseItemsResponse* response, std::function<void(::grpc::Status)>) override;
      void ReleaseItems(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest* request, ::inventory::ReleaseItemsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ProcessCustomerOrder(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest* request, ::inventory::ProcessCustomerOrderResponse* response, std::function<void(::grpc::Status)>) override;
      void ProcessCustomerOrder(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest* request, ::inventory::ProcessCustomerOrderResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RestockItemsOrder(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest* request, ::inventory::RestockItemsOrderResponse* response, std::function<void(::grpc::Status)>) override;
      void RestockItemsOrder(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest* request, ::inventory::RestockItemsOrderResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReportJobStatus(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest* request, ::inventory::ReportJobStatusResponse* response, std::function<void(::grpc::Status)>) override;
      void ReportJobStatus(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest* request, ::inventory::ReportJobStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::inventory::CheckAvailabilityResponse>* AsyncCheckAvailabilityRaw(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::inventory::CheckAvailabilityResponse>* PrepareAsyncCheckAvailabilityRaw(::grpc::ClientContext* context, const ::inventory::CheckAvailabilityRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::inventory::ReserveItemsResponse>* AsyncReserveItemsRaw(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::inventory::ReserveItemsResponse>* PrepareAsyncReserveItemsRaw(::grpc::ClientContext* context, const ::inventory::ReserveItemsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::inventory::ReleaseItemsResponse>* AsyncReleaseItemsRaw(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::inventory::ReleaseItemsResponse>* PrepareAsyncReleaseItemsRaw(::grpc::ClientContext* context, const ::inventory::ReleaseItemsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::inventory::ProcessCustomerOrderResponse>* AsyncProcessCustomerOrderRaw(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::inventory::ProcessCustomerOrderResponse>* PrepareAsyncProcessCustomerOrderRaw(::grpc::ClientContext* context, const ::inventory::ProcessCustomerOrderRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::inventory::RestockItemsOrderResponse>* AsyncRestockItemsOrderRaw(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::inventory::RestockItemsOrderResponse>* PrepareAsyncRestockItemsOrderRaw(::grpc::ClientContext* context, const ::inventory::RestockItemsOrderRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::inventory::ReportJobStatusResponse>* AsyncReportJobStatusRaw(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::inventory::ReportJobStatusResponse>* PrepareAsyncReportJobStatusRaw(::grpc::ClientContext* context, const ::inventory::ReportJobStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CheckAvailability_;
    const ::grpc::internal::RpcMethod rpcmethod_ReserveItems_;
    const ::grpc::internal::RpcMethod rpcmethod_ReleaseItems_;
    const ::grpc::internal::RpcMethod rpcmethod_ProcessCustomerOrder_;
    const ::grpc::internal::RpcMethod rpcmethod_RestockItemsOrder_;
    const ::grpc::internal::RpcMethod rpcmethod_ReportJobStatus_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CheckAvailability(::grpc::ServerContext* context, const ::inventory::CheckAvailabilityRequest* request, ::inventory::CheckAvailabilityResponse* response);
    virtual ::grpc::Status ReserveItems(::grpc::ServerContext* context, const ::inventory::ReserveItemsRequest* request, ::inventory::ReserveItemsResponse* response);
    virtual ::grpc::Status ReleaseItems(::grpc::ServerContext* context, const ::inventory::ReleaseItemsRequest* request, ::inventory::ReleaseItemsResponse* response);
    virtual ::grpc::Status ProcessCustomerOrder(::grpc::ServerContext* context, const ::inventory::ProcessCustomerOrderRequest* request, ::inventory::ProcessCustomerOrderResponse* response);
    virtual ::grpc::Status RestockItemsOrder(::grpc::ServerContext* context, const ::inventory::RestockItemsOrderRequest* request, ::inventory::RestockItemsOrderResponse* response);
    virtual ::grpc::Status ReportJobStatus(::grpc::ServerContext* context, const ::inventory::ReportJobStatusRequest* request, ::inventory::ReportJobStatusResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CheckAvailability : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CheckAvailability() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CheckAvailability() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckAvailability(::grpc::ServerContext* /*context*/, const ::inventory::CheckAvailabilityRequest* /*request*/, ::inventory::CheckAvailabilityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckAvailability(::grpc::ServerContext* context, ::inventory::CheckAvailabilityRequest* request, ::grpc::ServerAsyncResponseWriter< ::inventory::CheckAvailabilityResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReserveItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReserveItems() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ReserveItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReserveItems(::grpc::ServerContext* /*context*/, const ::inventory::ReserveItemsRequest* /*request*/, ::inventory::ReserveItemsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReserveItems(::grpc::ServerContext* context, ::inventory::ReserveItemsRequest* request, ::grpc::ServerAsyncResponseWriter< ::inventory::ReserveItemsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReleaseItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReleaseItems() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ReleaseItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReleaseItems(::grpc::ServerContext* /*context*/, const ::inventory::ReleaseItemsRequest* /*request*/, ::inventory::ReleaseItemsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReleaseItems(::grpc::ServerContext* context, ::inventory::ReleaseItemsRequest* request, ::grpc::ServerAsyncResponseWriter< ::inventory::ReleaseItemsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ProcessCustomerOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ProcessCustomerOrder() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_ProcessCustomerOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessCustomerOrder(::grpc::ServerContext* /*context*/, const ::inventory::ProcessCustomerOrderRequest* /*request*/, ::inventory::ProcessCustomerOrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessCustomerOrder(::grpc::ServerContext* context, ::inventory::ProcessCustomerOrderRequest* request, ::grpc::ServerAsyncResponseWriter< ::inventory::ProcessCustomerOrderResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RestockItemsOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RestockItemsOrder() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_RestockItemsOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RestockItemsOrder(::grpc::ServerContext* /*context*/, const ::inventory::RestockItemsOrderRequest* /*request*/, ::inventory::RestockItemsOrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRestockItemsOrder(::grpc::ServerContext* context, ::inventory::RestockItemsOrderRequest* request, ::grpc::ServerAsyncResponseWriter< ::inventory::RestockItemsOrderResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReportJobStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReportJobStatus() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_ReportJobStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportJobStatus(::grpc::ServerContext* /*context*/, const ::inventory::ReportJobStatusRequest* /*request*/, ::inventory::ReportJobStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportJobStatus(::grpc::ServerContext* context, ::inventory::ReportJobStatusRequest* request, ::grpc::ServerAsyncResponseWriter< ::inventory::ReportJobStatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CheckAvailability<WithAsyncMethod_ReserveItems<WithAsyncMethod_ReleaseItems<WithAsyncMethod_ProcessCustomerOrder<WithAsyncMethod_RestockItemsOrder<WithAsyncMethod_ReportJobStatus<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CheckAvailability : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CheckAvailability() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::inventory::CheckAvailabilityRequest, ::inventory::CheckAvailabilityResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::inventory::CheckAvailabilityRequest* request, ::inventory::CheckAvailabilityResponse* response) { return this->CheckAvailability(context, request, response); }));}
    void SetMessageAllocatorFor_CheckAvailability(
        ::grpc::MessageAllocator< ::inventory::CheckAvailabilityRequest, ::inventory::CheckAvailabilityResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::inventory::CheckAvailabilityRequest, ::inventory::CheckAvailabilityResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CheckAvailability() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckAvailability(::grpc::ServerContext* /*context*/, const ::inventory::CheckAvailabilityRequest* /*request*/, ::inventory::CheckAvailabilityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckAvailability(
      ::grpc::CallbackServerContext* /*context*/, const ::inventory::CheckAvailabilityRequest* /*request*/, ::inventory::CheckAvailabilityResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReserveItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReserveItems() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::inventory::ReserveItemsRequest, ::inventory::ReserveItemsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::inventory::ReserveItemsRequest* request, ::inventory::ReserveItemsResponse* response) { return this->ReserveItems(context, request, response); }));}
    void SetMessageAllocatorFor_ReserveItems(
        ::grpc::MessageAllocator< ::inventory::ReserveItemsRequest, ::inventory::ReserveItemsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::inventory::ReserveItemsRequest, ::inventory::ReserveItemsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReserveItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReserveItems(::grpc::ServerContext* /*context*/, const ::inventory::ReserveItemsRequest* /*request*/, ::inventory::ReserveItemsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReserveItems(
      ::grpc::CallbackServerContext* /*context*/, const ::inventory::ReserveItemsRequest* /*request*/, ::inventory::ReserveItemsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReleaseItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReleaseItems() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::inventory::ReleaseItemsRequest, ::inventory::ReleaseItemsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::inventory::ReleaseItemsRequest* request, ::inventory::ReleaseItemsResponse* response) { return this->ReleaseItems(context, request, response); }));}
    void SetMessageAllocatorFor_ReleaseItems(
        ::grpc::MessageAllocator< ::inventory::ReleaseItemsRequest, ::inventory::ReleaseItemsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::inventory::ReleaseItemsRequest, ::inventory::ReleaseItemsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReleaseItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReleaseItems(::grpc::ServerContext* /*context*/, const ::inventory::ReleaseItemsRequest* /*request*/, ::inventory::ReleaseItemsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReleaseItems(
      ::grpc::CallbackServerContext* /*context*/, const ::inventory::ReleaseItemsRequest* /*request*/, ::inventory::ReleaseItemsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ProcessCustomerOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ProcessCustomerOrder() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::inventory::ProcessCustomerOrderRequest, ::inventory::ProcessCustomerOrderResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::inventory::ProcessCustomerOrderRequest* request, ::inventory::ProcessCustomerOrderResponse* response) { return this->ProcessCustomerOrder(context, request, response); }));}
    void SetMessageAllocatorFor_ProcessCustomerOrder(
        ::grpc::MessageAllocator< ::inventory::ProcessCustomerOrderRequest, ::inventory::ProcessCustomerOrderResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::inventory::ProcessCustomerOrderRequest, ::inventory::ProcessCustomerOrderResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ProcessCustomerOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessCustomerOrder(::grpc::ServerContext* /*context*/, const ::inventory::ProcessCustomerOrderRequest* /*request*/, ::inventory::ProcessCustomerOrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ProcessCustomerOrder(
      ::grpc::CallbackServerContext* /*context*/, const ::inventory::ProcessCustomerOrderRequest* /*request*/, ::inventory::ProcessCustomerOrderResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RestockItemsOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RestockItemsOrder() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::inventory::RestockItemsOrderRequest, ::inventory::RestockItemsOrderResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::inventory::RestockItemsOrderRequest* request, ::inventory::RestockItemsOrderResponse* response) { return this->RestockItemsOrder(context, request, response); }));}
    void SetMessageAllocatorFor_RestockItemsOrder(
        ::grpc::MessageAllocator< ::inventory::RestockItemsOrderRequest, ::inventory::RestockItemsOrderResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::inventory::RestockItemsOrderRequest, ::inventory::RestockItemsOrderResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RestockItemsOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RestockItemsOrder(::grpc::ServerContext* /*context*/, const ::inventory::RestockItemsOrderRequest* /*request*/, ::inventory::RestockItemsOrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RestockItemsOrder(
      ::grpc::CallbackServerContext* /*context*/, const ::inventory::RestockItemsOrderRequest* /*request*/, ::inventory::RestockItemsOrderResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReportJobStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReportJobStatus() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::inventory::ReportJobStatusRequest, ::inventory::ReportJobStatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::inventory::ReportJobStatusRequest* request, ::inventory::ReportJobStatusResponse* response) { return this->ReportJobStatus(context, request, response); }));}
    void SetMessageAllocatorFor_ReportJobStatus(
        ::grpc::MessageAllocator< ::inventory::ReportJobStatusRequest, ::inventory::ReportJobStatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::inventory::ReportJobStatusRequest, ::inventory::ReportJobStatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReportJobStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportJobStatus(::grpc::ServerContext* /*context*/, const ::inventory::ReportJobStatusRequest* /*request*/, ::inventory::ReportJobStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportJobStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::inventory::ReportJobStatusRequest* /*request*/, ::inventory::ReportJobStatusResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CheckAvailability<WithCallbackMethod_ReserveItems<WithCallbackMethod_ReleaseItems<WithCallbackMethod_ProcessCustomerOrder<WithCallbackMethod_RestockItemsOrder<WithCallbackMethod_ReportJobStatus<Service > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CheckAvailability : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CheckAvailability() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CheckAvailability() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckAvailability(::grpc::ServerContext* /*context*/, const ::inventory::CheckAvailabilityRequest* /*request*/, ::inventory::CheckAvailabilityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReserveItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReserveItems() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ReserveItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReserveItems(::grpc::ServerContext* /*context*/, const ::inventory::ReserveItemsRequest* /*request*/, ::inventory::ReserveItemsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReleaseItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReleaseItems() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ReleaseItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReleaseItems(::grpc::ServerContext* /*context*/, const ::inventory::ReleaseItemsRequest* /*request*/, ::inventory::ReleaseItemsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ProcessCustomerOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ProcessCustomerOrder() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_ProcessCustomerOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessCustomerOrder(::grpc::ServerContext* /*context*/, const ::inventory::ProcessCustomerOrderRequest* /*request*/, ::inventory::ProcessCustomerOrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RestockItemsOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RestockItemsOrder() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_RestockItemsOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RestockItemsOrder(::grpc::ServerContext* /*context*/, const ::inventory::RestockItemsOrderRequest* /*request*/, ::inventory::RestockItemsOrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReportJobStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReportJobStatus() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_ReportJobStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportJobStatus(::grpc::ServerContext* /*context*/, const ::inventory::ReportJobStatusRequest* /*request*/, ::inventory::ReportJobStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CheckAvailability : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CheckAvailability() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CheckAvailability() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckAvailability(::grpc::ServerContext* /*context*/, const ::inventory::CheckAvailabilityRequest* /*request*/, ::inventory::CheckAvailabilityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckAvailability(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReserveItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReserveItems() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ReserveItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReserveItems(::grpc::ServerContext* /*context*/, const ::inventory::ReserveItemsRequest* /*request*/, ::inventory::ReserveItemsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReserveItems(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReleaseItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReleaseItems() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ReleaseItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReleaseItems(::grpc::ServerContext* /*context*/, const ::inventory::ReleaseItemsRequest* /*request*/, ::inventory::ReleaseItemsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReleaseItems(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ProcessCustomerOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ProcessCustomerOrder() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_ProcessCustomerOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessCustomerOrder(::grpc::ServerContext* /*context*/, const ::inventory::ProcessCustomerOrderRequest* /*request*/, ::inventory::ProcessCustomerOrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessCustomerOrder(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RestockItemsOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RestockItemsOrder() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_RestockItemsOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RestockItemsOrder(::grpc::ServerContext* /*context*/, const ::inventory::RestockItemsOrderRequest* /*request*/, ::inventory::RestockItemsOrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRestockItemsOrder(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReportJobStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReportJobStatus() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_ReportJobStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportJobStatus(::grpc::ServerContext* /*context*/, const ::inventory::ReportJobStatusRequest* /*request*/, ::inventory::ReportJobStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportJobStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CheckAvailability : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CheckAvailability() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CheckAvailability(context, request, response); }));
    }
    ~WithRawCallbackMethod_CheckAvailability() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckAvailability(::grpc::ServerContext* /*context*/, const ::inventory::CheckAvailabilityRequest* /*request*/, ::inventory::CheckAvailabilityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckAvailability(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReserveItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReserveItems() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReserveItems(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReserveItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReserveItems(::grpc::ServerContext* /*context*/, const ::inventory::ReserveItemsRequest* /*request*/, ::inventory::ReserveItemsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReserveItems(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReleaseItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReleaseItems() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReleaseItems(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReleaseItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReleaseItems(::grpc::ServerContext* /*context*/, const ::inventory::ReleaseItemsRequest* /*request*/, ::inventory::ReleaseItemsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReleaseItems(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ProcessCustomerOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ProcessCustomerOrder() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ProcessCustomerOrder(context, request, response); }));
    }
    ~WithRawCallbackMethod_ProcessCustomerOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessCustomerOrder(::grpc::ServerContext* /*context*/, const ::inventory::ProcessCustomerOrderRequest* /*request*/, ::inventory::ProcessCustomerOrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ProcessCustomerOrder(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RestockItemsOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RestockItemsOrder() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RestockItemsOrder(context, request, response); }));
    }
    ~WithRawCallbackMethod_RestockItemsOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RestockItemsOrder(::grpc::ServerContext* /*context*/, const ::inventory::RestockItemsOrderRequest* /*request*/, ::inventory::RestockItemsOrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RestockItemsOrder(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReportJobStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReportJobStatus() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReportJobStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReportJobStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportJobStatus(::grpc::ServerContext* /*context*/, const ::inventory::ReportJobStatusRequest* /*request*/, ::inventory::ReportJobStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportJobStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CheckAvailability : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CheckAvailability() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::inventory::CheckAvailabilityRequest, ::inventory::CheckAvailabilityResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::inventory::CheckAvailabilityRequest, ::inventory::CheckAvailabilityResponse>* streamer) {
                       return this->StreamedCheckAvailability(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CheckAvailability() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CheckAvailability(::grpc::ServerContext* /*context*/, const ::inventory::CheckAvailabilityRequest* /*request*/, ::inventory::CheckAvailabilityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCheckAvailability(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::inventory::CheckAvailabilityRequest,::inventory::CheckAvailabilityResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReserveItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReserveItems() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::inventory::ReserveItemsRequest, ::inventory::ReserveItemsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::inventory::ReserveItemsRequest, ::inventory::ReserveItemsResponse>* streamer) {
                       return this->StreamedReserveItems(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReserveItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReserveItems(::grpc::ServerContext* /*context*/, const ::inventory::ReserveItemsRequest* /*request*/, ::inventory::ReserveItemsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReserveItems(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::inventory::ReserveItemsRequest,::inventory::ReserveItemsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReleaseItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReleaseItems() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::inventory::ReleaseItemsRequest, ::inventory::ReleaseItemsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::inventory::ReleaseItemsRequest, ::inventory::ReleaseItemsResponse>* streamer) {
                       return this->StreamedReleaseItems(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReleaseItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReleaseItems(::grpc::ServerContext* /*context*/, const ::inventory::ReleaseItemsRequest* /*request*/, ::inventory::ReleaseItemsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReleaseItems(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::inventory::ReleaseItemsRequest,::inventory::ReleaseItemsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ProcessCustomerOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ProcessCustomerOrder() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::inventory::ProcessCustomerOrderRequest, ::inventory::ProcessCustomerOrderResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::inventory::ProcessCustomerOrderRequest, ::inventory::ProcessCustomerOrderResponse>* streamer) {
                       return this->StreamedProcessCustomerOrder(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ProcessCustomerOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ProcessCustomerOrder(::grpc::ServerContext* /*context*/, const ::inventory::ProcessCustomerOrderRequest* /*request*/, ::inventory::ProcessCustomerOrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedProcessCustomerOrder(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::inventory::ProcessCustomerOrderRequest,::inventory::ProcessCustomerOrderResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RestockItemsOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RestockItemsOrder() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::inventory::RestockItemsOrderRequest, ::inventory::RestockItemsOrderResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::inventory::RestockItemsOrderRequest, ::inventory::RestockItemsOrderResponse>* streamer) {
                       return this->StreamedRestockItemsOrder(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RestockItemsOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RestockItemsOrder(::grpc::ServerContext* /*context*/, const ::inventory::RestockItemsOrderRequest* /*request*/, ::inventory::RestockItemsOrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRestockItemsOrder(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::inventory::RestockItemsOrderRequest,::inventory::RestockItemsOrderResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReportJobStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReportJobStatus() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::inventory::ReportJobStatusRequest, ::inventory::ReportJobStatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::inventory::ReportJobStatusRequest, ::inventory::ReportJobStatusResponse>* streamer) {
                       return this->StreamedReportJobStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReportJobStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReportJobStatus(::grpc::ServerContext* /*context*/, const ::inventory::ReportJobStatusRequest* /*request*/, ::inventory::ReportJobStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReportJobStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::inventory::ReportJobStatusRequest,::inventory::ReportJobStatusResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CheckAvailability<WithStreamedUnaryMethod_ReserveItems<WithStreamedUnaryMethod_ReleaseItems<WithStreamedUnaryMethod_ProcessCustomerOrder<WithStreamedUnaryMethod_RestockItemsOrder<WithStreamedUnaryMethod_ReportJobStatus<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CheckAvailability<WithStreamedUnaryMethod_ReserveItems<WithStreamedUnaryMethod_ReleaseItems<WithStreamedUnaryMethod_ProcessCustomerOrder<WithStreamedUnaryMethod_RestockItemsOrder<WithStreamedUnaryMethod_ReportJobStatus<Service > > > > > > StreamedService;
};

}  // namespace inventory


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_proto_2finventory_2eproto__INCLUDED
