// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ANALYTICS_ANALYTICSMESSAGES_H_
#define FLATBUFFERS_GENERATED_ANALYTICS_ANALYTICSMESSAGES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace AnalyticsMessages {

struct OrderMetric;
struct OrderMetricBuilder;

struct OrderMetric FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OrderMetricBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ORDER_ID = 4,
    VT_STATUS = 6,
    VT_DURATION_SECONDS = 8,
    VT_TIMESTAMP = 10
  };
  const ::flatbuffers::String *order_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ORDER_ID);
  }
  const ::flatbuffers::String *status() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STATUS);
  }
  double duration_seconds() const {
    return GetField<double>(VT_DURATION_SECONDS, 0.0);
  }
  int64_t timestamp() const {
    return GetField<int64_t>(VT_TIMESTAMP, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ORDER_ID) &&
           verifier.VerifyString(order_id()) &&
           VerifyOffset(verifier, VT_STATUS) &&
           verifier.VerifyString(status()) &&
           VerifyField<double>(verifier, VT_DURATION_SECONDS, 8) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct OrderMetricBuilder {
  typedef OrderMetric Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_order_id(::flatbuffers::Offset<::flatbuffers::String> order_id) {
    fbb_.AddOffset(OrderMetric::VT_ORDER_ID, order_id);
  }
  void add_status(::flatbuffers::Offset<::flatbuffers::String> status) {
    fbb_.AddOffset(OrderMetric::VT_STATUS, status);
  }
  void add_duration_seconds(double duration_seconds) {
    fbb_.AddElement<double>(OrderMetric::VT_DURATION_SECONDS, duration_seconds, 0.0);
  }
  void add_timestamp(int64_t timestamp) {
    fbb_.AddElement<int64_t>(OrderMetric::VT_TIMESTAMP, timestamp, 0);
  }
  explicit OrderMetricBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<OrderMetric> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<OrderMetric>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<OrderMetric> CreateOrderMetric(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> order_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> status = 0,
    double duration_seconds = 0.0,
    int64_t timestamp = 0) {
  OrderMetricBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_duration_seconds(duration_seconds);
  builder_.add_status(status);
  builder_.add_order_id(order_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<OrderMetric> CreateOrderMetricDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *order_id = nullptr,
    const char *status = nullptr,
    double duration_seconds = 0.0,
    int64_t timestamp = 0) {
  auto order_id__ = order_id ? _fbb.CreateString(order_id) : 0;
  auto status__ = status ? _fbb.CreateString(status) : 0;
  return AnalyticsMessages::CreateOrderMetric(
      _fbb,
      order_id__,
      status__,
      duration_seconds,
      timestamp);
}

inline const AnalyticsMessages::OrderMetric *GetOrderMetric(const void *buf) {
  return ::flatbuffers::GetRoot<AnalyticsMessages::OrderMetric>(buf);
}

inline const AnalyticsMessages::OrderMetric *GetSizePrefixedOrderMetric(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<AnalyticsMessages::OrderMetric>(buf);
}

template <bool B = false>
inline bool VerifyOrderMetricBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<AnalyticsMessages::OrderMetric>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedOrderMetricBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<AnalyticsMessages::OrderMetric>(nullptr);
}

inline void FinishOrderMetricBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<AnalyticsMessages::OrderMetric> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedOrderMetricBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<AnalyticsMessages::OrderMetric> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace AnalyticsMessages

#endif  // FLATBUFFERS_GENERATED_ANALYTICS_ANALYTICSMESSAGES_H_
