// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AnalyticsMessages

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OrderMetric struct {
	_tab flatbuffers.Table
}

func GetRootAsOrderMetric(buf []byte, offset flatbuffers.UOffsetT) *OrderMetric {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OrderMetric{}
	x.Init(buf, n+offset)
	return x
}

func FinishOrderMetricBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOrderMetric(buf []byte, offset flatbuffers.UOffsetT) *OrderMetric {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OrderMetric{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOrderMetricBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OrderMetric) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OrderMetric) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OrderMetric) OrderId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OrderMetric) Status() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OrderMetric) DurationSeconds() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *OrderMetric) MutateDurationSeconds(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func (rcv *OrderMetric) Timestamp() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderMetric) MutateTimestamp(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func OrderMetricStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func OrderMetricAddOrderId(builder *flatbuffers.Builder, orderId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(orderId), 0)
}
func OrderMetricAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(status), 0)
}
func OrderMetricAddDurationSeconds(builder *flatbuffers.Builder, durationSeconds float64) {
	builder.PrependFloat64Slot(2, durationSeconds, 0.0)
}
func OrderMetricAddTimestamp(builder *flatbuffers.Builder, timestamp int64) {
	builder.PrependInt64Slot(3, timestamp, 0)
}
func OrderMetricEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
