// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package RobotMessages

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OrderBroadcast struct {
	_tab flatbuffers.Table
}

func GetRootAsOrderBroadcast(buf []byte, offset flatbuffers.UOffsetT) *OrderBroadcast {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OrderBroadcast{}
	x.Init(buf, n+offset)
	return x
}

func FinishOrderBroadcastBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOrderBroadcast(buf []byte, offset flatbuffers.UOffsetT) *OrderBroadcast {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OrderBroadcast{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOrderBroadcastBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OrderBroadcast) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OrderBroadcast) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OrderBroadcast) OrderId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OrderBroadcast) OrderType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OrderBroadcast) Items(obj *Item, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *OrderBroadcast) ItemsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func OrderBroadcastStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func OrderBroadcastAddOrderId(builder *flatbuffers.Builder, orderId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(orderId), 0)
}
func OrderBroadcastAddOrderType(builder *flatbuffers.Builder, orderType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(orderType), 0)
}
func OrderBroadcastAddItems(builder *flatbuffers.Builder, items flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(items), 0)
}
func OrderBroadcastStartItemsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func OrderBroadcastEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
