// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: inventory/proto/inventory.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_CheckAvailability_FullMethodName   = "/inventory.InventoryService/CheckAvailability"
	InventoryService_ReserveItems_FullMethodName        = "/inventory.InventoryService/ReserveItems"
	InventoryService_ReleaseItems_FullMethodName        = "/inventory.InventoryService/ReleaseItems"
	InventoryService_RestockItems_FullMethodName        = "/inventory.InventoryService/RestockItems"
	InventoryService_ReportJobStatus_FullMethodName     = "/inventory.InventoryService/ReportJobStatus"
	InventoryService_BillAndPay_FullMethodName          = "/inventory.InventoryService/BillAndPay"
	InventoryService_GetInventoryMetrics_FullMethodName = "/inventory.InventoryService/GetInventoryMetrics"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryServiceClient interface {
	CheckAvailability(ctx context.Context, in *CheckAvailabilityRequest, opts ...grpc.CallOption) (*CheckAvailabilityResponse, error)
	ReserveItems(ctx context.Context, in *ReserveItemsRequest, opts ...grpc.CallOption) (*ReserveItemsResponse, error)
	ReleaseItems(ctx context.Context, in *ReleaseItemsRequest, opts ...grpc.CallOption) (*ReleaseItemsResponse, error)
	RestockItems(ctx context.Context, in *RestockItemsRequest, opts ...grpc.CallOption) (*RestockItemsResponse, error)
	ReportJobStatus(ctx context.Context, in *ReportJobStatusRequest, opts ...grpc.CallOption) (*ReportJobStatusResponse, error)
	BillAndPay(ctx context.Context, in *BillRequest, opts ...grpc.CallOption) (*BillResponse, error)
	GetInventoryMetrics(ctx context.Context, in *GetInventoryMetricsRequest, opts ...grpc.CallOption) (*GetInventoryMetricsResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) CheckAvailability(ctx context.Context, in *CheckAvailabilityRequest, opts ...grpc.CallOption) (*CheckAvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAvailabilityResponse)
	err := c.cc.Invoke(ctx, InventoryService_CheckAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ReserveItems(ctx context.Context, in *ReserveItemsRequest, opts ...grpc.CallOption) (*ReserveItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveItemsResponse)
	err := c.cc.Invoke(ctx, InventoryService_ReserveItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ReleaseItems(ctx context.Context, in *ReleaseItemsRequest, opts ...grpc.CallOption) (*ReleaseItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseItemsResponse)
	err := c.cc.Invoke(ctx, InventoryService_ReleaseItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) RestockItems(ctx context.Context, in *RestockItemsRequest, opts ...grpc.CallOption) (*RestockItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestockItemsResponse)
	err := c.cc.Invoke(ctx, InventoryService_RestockItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ReportJobStatus(ctx context.Context, in *ReportJobStatusRequest, opts ...grpc.CallOption) (*ReportJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportJobStatusResponse)
	err := c.cc.Invoke(ctx, InventoryService_ReportJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) BillAndPay(ctx context.Context, in *BillRequest, opts ...grpc.CallOption) (*BillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BillResponse)
	err := c.cc.Invoke(ctx, InventoryService_BillAndPay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetInventoryMetrics(ctx context.Context, in *GetInventoryMetricsRequest, opts ...grpc.CallOption) (*GetInventoryMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInventoryMetricsResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetInventoryMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
type InventoryServiceServer interface {
	CheckAvailability(context.Context, *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error)
	ReserveItems(context.Context, *ReserveItemsRequest) (*ReserveItemsResponse, error)
	ReleaseItems(context.Context, *ReleaseItemsRequest) (*ReleaseItemsResponse, error)
	RestockItems(context.Context, *RestockItemsRequest) (*RestockItemsResponse, error)
	ReportJobStatus(context.Context, *ReportJobStatusRequest) (*ReportJobStatusResponse, error)
	BillAndPay(context.Context, *BillRequest) (*BillResponse, error)
	GetInventoryMetrics(context.Context, *GetInventoryMetricsRequest) (*GetInventoryMetricsResponse, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) CheckAvailability(context.Context, *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAvailability not implemented")
}
func (UnimplementedInventoryServiceServer) ReserveItems(context.Context, *ReserveItemsRequest) (*ReserveItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveItems not implemented")
}
func (UnimplementedInventoryServiceServer) ReleaseItems(context.Context, *ReleaseItemsRequest) (*ReleaseItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseItems not implemented")
}
func (UnimplementedInventoryServiceServer) RestockItems(context.Context, *RestockItemsRequest) (*RestockItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestockItems not implemented")
}
func (UnimplementedInventoryServiceServer) ReportJobStatus(context.Context, *ReportJobStatusRequest) (*ReportJobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportJobStatus not implemented")
}
func (UnimplementedInventoryServiceServer) BillAndPay(context.Context, *BillRequest) (*BillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BillAndPay not implemented")
}
func (UnimplementedInventoryServiceServer) GetInventoryMetrics(context.Context, *GetInventoryMetricsRequest) (*GetInventoryMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventoryMetrics not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call panics, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_CheckAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CheckAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CheckAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CheckAvailability(ctx, req.(*CheckAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ReserveItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ReserveItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ReserveItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ReserveItems(ctx, req.(*ReserveItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ReleaseItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ReleaseItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ReleaseItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ReleaseItems(ctx, req.(*ReleaseItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_RestockItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestockItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).RestockItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_RestockItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).RestockItems(ctx, req.(*RestockItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ReportJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ReportJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ReportJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ReportJobStatus(ctx, req.(*ReportJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_BillAndPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).BillAndPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_BillAndPay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).BillAndPay(ctx, req.(*BillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetInventoryMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetInventoryMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetInventoryMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetInventoryMetrics(ctx, req.(*GetInventoryMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAvailability",
			Handler:    _InventoryService_CheckAvailability_Handler,
		},
		{
			MethodName: "ReserveItems",
			Handler:    _InventoryService_ReserveItems_Handler,
		},
		{
			MethodName: "ReleaseItems",
			Handler:    _InventoryService_ReleaseItems_Handler,
		},
		{
			MethodName: "RestockItems",
			Handler:    _InventoryService_RestockItems_Handler,
		},
		{
			MethodName: "ReportJobStatus",
			Handler:    _InventoryService_ReportJobStatus_Handler,
		},
		{
			MethodName: "BillAndPay",
			Handler:    _InventoryService_BillAndPay_Handler,
		},
		{
			MethodName: "GetInventoryMetrics",
			Handler:    _InventoryService_GetInventoryMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/proto/inventory.proto",
}
