// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: inventory/proto/inventory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skus          []string               `protobuf:"bytes,1,rep,name=skus,proto3" json:"skus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityRequest) Reset() {
	*x = CheckAvailabilityRequest{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityRequest) ProtoMessage() {}

func (x *CheckAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAvailabilityRequest) GetSkus() []string {
	if x != nil {
		return x.Skus
	}
	return nil
}

type CheckAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         map[string]*ItemDetail `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityResponse) Reset() {
	*x = CheckAvailabilityResponse{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityResponse) ProtoMessage() {}

func (x *CheckAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAvailabilityResponse) GetItems() map[string]*ItemDetail {
	if x != nil {
		return x.Items
	}
	return nil
}

type ItemDetail struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Sku               string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AisleType         string                 `protobuf:"bytes,3,opt,name=aisle_type,json=aisleType,proto3" json:"aisle_type,omitempty"`
	QuantityAvailable int32                  `protobuf:"varint,4,opt,name=quantity_available,json=quantityAvailable,proto3" json:"quantity_available,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ItemDetail) Reset() {
	*x = ItemDetail{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDetail) ProtoMessage() {}

func (x *ItemDetail) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDetail.ProtoReflect.Descriptor instead.
func (*ItemDetail) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *ItemDetail) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ItemDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemDetail) GetAisleType() string {
	if x != nil {
		return x.AisleType
	}
	return ""
}

func (x *ItemDetail) GetQuantityAvailable() int32 {
	if x != nil {
		return x.QuantityAvailable
	}
	return 0
}

type ReserveItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         map[string]int32       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItemsRequest) Reset() {
	*x = ReserveItemsRequest{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItemsRequest) ProtoMessage() {}

func (x *ReserveItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItemsRequest.ProtoReflect.Descriptor instead.
func (*ReserveItemsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveItemsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveItemsRequest) GetItems() map[string]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReserveItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         map[string]int32       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"` // True if operation succeeded (even partial), False if DB error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItemsResponse) Reset() {
	*x = ReserveItemsResponse{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItemsResponse) ProtoMessage() {}

func (x *ReserveItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItemsResponse.ProtoReflect.Descriptor instead.
func (*ReserveItemsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveItemsResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveItemsResponse) GetItems() map[string]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReserveItemsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReleaseItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         map[string]int32       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseItemsRequest) Reset() {
	*x = ReleaseItemsRequest{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseItemsRequest) ProtoMessage() {}

func (x *ReleaseItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseItemsRequest.ProtoReflect.Descriptor instead.
func (*ReleaseItemsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseItemsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReleaseItemsRequest) GetItems() map[string]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReleaseItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // True if items were successfully returned to DB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseItemsResponse) Reset() {
	*x = ReleaseItemsResponse{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseItemsResponse) ProtoMessage() {}

func (x *ReleaseItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseItemsResponse.ProtoReflect.Descriptor instead.
func (*ReleaseItemsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseItemsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RestockItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupplierId    string                 `protobuf:"bytes,1,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	Items         []*RestockItem         `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestockItemsRequest) Reset() {
	*x = RestockItemsRequest{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestockItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestockItemsRequest) ProtoMessage() {}

func (x *RestockItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestockItemsRequest.ProtoReflect.Descriptor instead.
func (*RestockItemsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *RestockItemsRequest) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *RestockItemsRequest) GetItems() []*RestockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RestockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AisleType     string                 `protobuf:"bytes,3,opt,name=aisle_type,json=aisleType,proto3" json:"aisle_type,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	MfdDate       string                 `protobuf:"bytes,5,opt,name=mfd_date,json=mfdDate,proto3" json:"mfd_date,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestockItem) Reset() {
	*x = RestockItem{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestockItem) ProtoMessage() {}

func (x *RestockItem) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestockItem.ProtoReflect.Descriptor instead.
func (*RestockItem) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *RestockItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *RestockItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestockItem) GetAisleType() string {
	if x != nil {
		return x.AisleType
	}
	return ""
}

func (x *RestockItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RestockItem) GetMfdDate() string {
	if x != nil {
		return x.MfdDate
	}
	return ""
}

func (x *RestockItem) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

type RestockItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // True if all items were processed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestockItemsResponse) Reset() {
	*x = RestockItemsResponse{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestockItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestockItemsResponse) ProtoMessage() {}

func (x *RestockItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestockItemsResponse.ProtoReflect.Descriptor instead.
func (*RestockItemsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *RestockItemsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReportJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	RobotId       string                 `protobuf:"bytes,2,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "SUCCESS", "NO_OP", "FAILED"
	Items         map[string]int32       `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportJobStatusRequest) Reset() {
	*x = ReportJobStatusRequest{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportJobStatusRequest) ProtoMessage() {}

func (x *ReportJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportJobStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *ReportJobStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReportJobStatusRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *ReportJobStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportJobStatusRequest) GetItems() map[string]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReportJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // True if the report was received and logged
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportJobStatusResponse) Reset() {
	*x = ReportJobStatusResponse{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportJobStatusResponse) ProtoMessage() {}

func (x *ReportJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportJobStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *ReportJobStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         map[string]int32       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Matches ReserveItemsRequest exactly
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *CheckoutRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CheckoutRequest) GetItems() map[string]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

type CheckoutResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OrderId string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Consistency: Matches ReserveItemsResponse exactly.
	// Use this map to call ReleaseItems if the user cancels.
	Items   map[string]int32 `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Success bool             `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	// The Bill (From Pricing Service)
	TotalPrice    float64 `protobuf:"fixed64,4,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutResponse) Reset() {
	*x = CheckoutResponse{}
	mi := &file_inventory_proto_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResponse) ProtoMessage() {}

func (x *CheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResponse.ProtoReflect.Descriptor instead.
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *CheckoutResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CheckoutResponse) GetItems() map[string]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CheckoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckoutResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

var File_inventory_proto_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1finventory/proto/inventory.proto\x12\tinventory\".\n" +
	"\x18CheckAvailabilityRequest\x12\x12\n" +
	"\x04skus\x18\x01 \x03(\tR\x04skus\"\xb3\x01\n" +
	"\x19CheckAvailabilityResponse\x12E\n" +
	"\x05items\x18\x01 \x03(\v2/.inventory.CheckAvailabilityResponse.ItemsEntryR\x05items\x1aO\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.inventory.ItemDetailR\x05value:\x028\x01\"\x80\x01\n" +
	"\n" +
	"ItemDetail\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"aisle_type\x18\x03 \x01(\tR\taisleType\x12-\n" +
	"\x12quantity_available\x18\x04 \x01(\x05R\x11quantityAvailable\"\xab\x01\n" +
	"\x13ReserveItemsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12?\n" +
	"\x05items\x18\x02 \x03(\v2).inventory.ReserveItemsRequest.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xc7\x01\n" +
	"\x14ReserveItemsResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12@\n" +
	"\x05items\x18\x02 \x03(\v2*.inventory.ReserveItemsResponse.ItemsEntryR\x05items\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xab\x01\n" +
	"\x13ReleaseItemsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12?\n" +
	"\x05items\x18\x02 \x03(\v2).inventory.ReleaseItemsRequest.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"0\n" +
	"\x14ReleaseItemsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"d\n" +
	"\x13RestockItemsRequest\x12\x1f\n" +
	"\vsupplier_id\x18\x01 \x01(\tR\n" +
	"supplierId\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.inventory.RestockItemR\x05items\"\xaa\x01\n" +
	"\vRestockItem\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"aisle_type\x18\x03 \x01(\tR\taisleType\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x19\n" +
	"\bmfd_date\x18\x05 \x01(\tR\amfdDate\x12\x1f\n" +
	"\vexpiry_date\x18\x06 \x01(\tR\n" +
	"expiryDate\"0\n" +
	"\x14RestockItemsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xe4\x01\n" +
	"\x16ReportJobStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x19\n" +
	"\brobot_id\x18\x02 \x01(\tR\arobotId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12B\n" +
	"\x05items\x18\x04 \x03(\v2,.inventory.ReportJobStatusRequest.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"3\n" +
	"\x17ReportJobStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa3\x01\n" +
	"\x0fCheckoutRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12;\n" +
	"\x05items\x18\x02 \x03(\v2%.inventory.CheckoutRequest.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xe0\x01\n" +
	"\x10CheckoutResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12<\n" +
	"\x05items\x18\x02 \x03(\v2&.inventory.CheckoutResponse.ItemsEntryR\x05items\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1f\n" +
	"\vtotal_price\x18\x04 \x01(\x01R\n" +
	"totalPrice\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012\x84\x04\n" +
	"\x10InventoryService\x12^\n" +
	"\x11CheckAvailability\x12#.inventory.CheckAvailabilityRequest\x1a$.inventory.CheckAvailabilityResponse\x12O\n" +
	"\fReserveItems\x12\x1e.inventory.ReserveItemsRequest\x1a\x1f.inventory.ReserveItemsResponse\x12O\n" +
	"\fReleaseItems\x12\x1e.inventory.ReleaseItemsRequest\x1a\x1f.inventory.ReleaseItemsResponse\x12O\n" +
	"\fRestockItems\x12\x1e.inventory.RestockItemsRequest\x1a\x1f.inventory.RestockItemsResponse\x12X\n" +
	"\x0fReportJobStatus\x12!.inventory.ReportJobStatusRequest\x1a\".inventory.ReportJobStatusResponse\x12C\n" +
	"\bCheckout\x12\x1a.inventory.CheckoutRequest\x1a\x1b.inventory.CheckoutResponseB\x1eZ\x1cauto_grocery/inventory/protob\x06proto3"

var (
	file_inventory_proto_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_inventory_proto_rawDescData []byte
)

func file_inventory_proto_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_inventory_proto_rawDesc), len(file_inventory_proto_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_inventory_proto_rawDescData
}

var file_inventory_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_inventory_proto_inventory_proto_goTypes = []any{
	(*CheckAvailabilityRequest)(nil),  // 0: inventory.CheckAvailabilityRequest
	(*CheckAvailabilityResponse)(nil), // 1: inventory.CheckAvailabilityResponse
	(*ItemDetail)(nil),                // 2: inventory.ItemDetail
	(*ReserveItemsRequest)(nil),       // 3: inventory.ReserveItemsRequest
	(*ReserveItemsResponse)(nil),      // 4: inventory.ReserveItemsResponse
	(*ReleaseItemsRequest)(nil),       // 5: inventory.ReleaseItemsRequest
	(*ReleaseItemsResponse)(nil),      // 6: inventory.ReleaseItemsResponse
	(*RestockItemsRequest)(nil),       // 7: inventory.RestockItemsRequest
	(*RestockItem)(nil),               // 8: inventory.RestockItem
	(*RestockItemsResponse)(nil),      // 9: inventory.RestockItemsResponse
	(*ReportJobStatusRequest)(nil),    // 10: inventory.ReportJobStatusRequest
	(*ReportJobStatusResponse)(nil),   // 11: inventory.ReportJobStatusResponse
	(*CheckoutRequest)(nil),           // 12: inventory.CheckoutRequest
	(*CheckoutResponse)(nil),          // 13: inventory.CheckoutResponse
	nil,                               // 14: inventory.CheckAvailabilityResponse.ItemsEntry
	nil,                               // 15: inventory.ReserveItemsRequest.ItemsEntry
	nil,                               // 16: inventory.ReserveItemsResponse.ItemsEntry
	nil,                               // 17: inventory.ReleaseItemsRequest.ItemsEntry
	nil,                               // 18: inventory.ReportJobStatusRequest.ItemsEntry
	nil,                               // 19: inventory.CheckoutRequest.ItemsEntry
	nil,                               // 20: inventory.CheckoutResponse.ItemsEntry
}
var file_inventory_proto_inventory_proto_depIdxs = []int32{
	14, // 0: inventory.CheckAvailabilityResponse.items:type_name -> inventory.CheckAvailabilityResponse.ItemsEntry
	15, // 1: inventory.ReserveItemsRequest.items:type_name -> inventory.ReserveItemsRequest.ItemsEntry
	16, // 2: inventory.ReserveItemsResponse.items:type_name -> inventory.ReserveItemsResponse.ItemsEntry
	17, // 3: inventory.ReleaseItemsRequest.items:type_name -> inventory.ReleaseItemsRequest.ItemsEntry
	8,  // 4: inventory.RestockItemsRequest.items:type_name -> inventory.RestockItem
	18, // 5: inventory.ReportJobStatusRequest.items:type_name -> inventory.ReportJobStatusRequest.ItemsEntry
	19, // 6: inventory.CheckoutRequest.items:type_name -> inventory.CheckoutRequest.ItemsEntry
	20, // 7: inventory.CheckoutResponse.items:type_name -> inventory.CheckoutResponse.ItemsEntry
	2,  // 8: inventory.CheckAvailabilityResponse.ItemsEntry.value:type_name -> inventory.ItemDetail
	0,  // 9: inventory.InventoryService.CheckAvailability:input_type -> inventory.CheckAvailabilityRequest
	3,  // 10: inventory.InventoryService.ReserveItems:input_type -> inventory.ReserveItemsRequest
	5,  // 11: inventory.InventoryService.ReleaseItems:input_type -> inventory.ReleaseItemsRequest
	7,  // 12: inventory.InventoryService.RestockItems:input_type -> inventory.RestockItemsRequest
	10, // 13: inventory.InventoryService.ReportJobStatus:input_type -> inventory.ReportJobStatusRequest
	12, // 14: inventory.InventoryService.Checkout:input_type -> inventory.CheckoutRequest
	1,  // 15: inventory.InventoryService.CheckAvailability:output_type -> inventory.CheckAvailabilityResponse
	4,  // 16: inventory.InventoryService.ReserveItems:output_type -> inventory.ReserveItemsResponse
	6,  // 17: inventory.InventoryService.ReleaseItems:output_type -> inventory.ReleaseItemsResponse
	9,  // 18: inventory.InventoryService.RestockItems:output_type -> inventory.RestockItemsResponse
	11, // 19: inventory.InventoryService.ReportJobStatus:output_type -> inventory.ReportJobStatusResponse
	13, // 20: inventory.InventoryService.Checkout:output_type -> inventory.CheckoutResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_inventory_proto_inventory_proto_init() }
func file_inventory_proto_inventory_proto_init() {
	if File_inventory_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_inventory_proto_rawDesc), len(file_inventory_proto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_proto_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto_inventory_proto = out.File
	file_inventory_proto_inventory_proto_goTypes = nil
	file_inventory_proto_inventory_proto_depIdxs = nil
}
